services:
  redis:
    image: redis:latest
    restart : always
    command: ["redis-server", "--appendonly", "yes", "--port", "6379"]
    container_name: redis_service
    hostname: redis_service
    networks:
      general_network:
        ipv4_address: 172.18.0.6
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      placement:
        constraints:
          - node.role == manager
          

volumes:
  redis_data:
    external: true

networks:
  general_network:
    external: true